  - name: apt-get update
    apt: update_cache=yes 
  - name: install tools
    apt: name=iftop,apachetop,mlocate,s3cmd,htop,xfsprogs,telnet,dsniff,iotop,dstat,tcpdump,schedtool,python-pip,unzip,nfs-common,lvm2,ncftp,sqlite3,nvme-cli state=latest
  - name: upgrade ubuntu
    apt: upgrade=dist update_cache=yes
  - name: Download sysdig installer
    get_url: url=https://s3.amazonaws.com/download.draios.com/stable/install-sysdig dest=/tmp/install-sysdig mode=0755
  - name: Execute sysdig installer 
    shell: /tmp/install-sysdig
