  - name: remove old docker
    apt:  name=docker,docker-engine,docker.io state=absent
  - name: apt-get install reqs 
    apt: name=apt-transport-https,ca-certificates,python-pip,curl,software-properties-common state=present
  - name: add key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present
  - name: add apt-repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
        state: present
        filename: 'docker'
  - name: apt-get update
    apt: update_cache=yes
  - name: modprobe aufs
    modprobe: name=aufs state=present
  - name: modprobe overlayfs 
    modprobe: name=overlayfs state=present
  - name: apt-get apparmor 
    apt: name=apparmor state=latest 
  - name: apt-get install docker-ce 
    apt: name=docker-ce state=present force=yes
  - name: start docker
    service: name=docker enabled=yes state=started
  - name: install docker-py
    pip: name=docker-py version=1.9
  - name: install docker compose
    get_url: url=https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755
